### ISSUE TITLE
样式错误

### ISSUE THREAD

**Issue by VonFry** [myst729/wp-reposidget#4]
下面有个地址。。
http://blog.vonfry.name/list/computer/program/language/javascript/451.php

OTL目测是CSS的问题，求教

**Comment by myst729** [comment]
http://blog.vonfry.name/wp-content/themes/VonfryThemes/css/single.css

第15行：
```.main .single_article .info {width: 100%; height: auto; left: 24px; margin:4px 1px 0 0}```
其中`width: 100%;`，因为FontAwesome图标类名`.info`和你自己的布局类名重名，把挂件标题挤到第二行了。
![222](https://cloud.githubusercontent.com/assets/519733/6631411/a18ecd42-c960-11e4-9d89-254d1edc2b5b.png)

第7行：
`overflow: hidden;`导致弹出提示无法显示，正常显示如下：
![111](https://cloud.githubusercontent.com/assets/519733/6631410/a156e1fc-c960-11e4-8ec6-aa163e27efc5.png)

**Comment by myst729** [comment]
解决方法，可以在你的single.css最后添加如下两行：

```css
.reposidget {overflow: visible !important}
.reposidget .info {width: auto !important}
```
